#!/usr/bin/env python3
"""Summarize the completed clean verify; never read credentials or fixture payloads."""
from pathlib import Path
import xml.etree.ElementTree as ET

for folder in ("surefire-reports", "failsafe-reports"):
    totals = dict(tests=0, failures=0, errors=0, skipped=0)
    for path in Path("target", folder).glob("TEST-*.xml"):
        root = ET.parse(path).getroot()
        for key in totals:
            totals[key] += int(root.get(key, 0))
    assert totals["tests"] > 0 and not any(totals[key] for key in ("failures", "errors", "skipped"))
    print(folder + ": " + ", ".join(f"{key}={value}" for key, value in totals.items()))

root = ET.parse("target/site/jacoco/jacoco.xml").getroot()
for package in root.findall("package"):
    if package.get("name", "").endswith(("census/domain", "census/application")):
        for counter in package.findall("counter"):
            kind = counter.get("type")
            if kind in ("LINE", "BRANCH"):
                covered, missed = int(counter.get("covered")), int(counter.get("missed"))
                percent = covered * 100 / (covered + missed)
                assert percent >= (85 if kind == "LINE" else 80)
                print(f"{package.get('name')}: {kind} {covered}/{covered + missed} ({percent:.2f}%)")

assert Path("target/openapi.json").read_bytes() == Path("docs/openapi/openapi.json").read_bytes()
print("OpenAPI generated by verify is byte-identical to the committed snapshot.")
for path in Path("target/failsafe-reports").glob("TEST-*DemoSeedsIT.xml"):
    names = [case.get("name") for case in ET.parse(path).getroot().findall("testcase")]
    assert "T_14_11_T_04_34_demoPendingRowsAreReviewableAndPreserveSubsequentEdits" in names
    print("PASS T_14_11_T_04_34_demoPendingRowsAreReviewableAndPreserveSubsequentEdits")
