package com.agilityhub.core.platform.application.audit;

/** Implemented subset of the closed action list in S14 R-14-09. */
public enum AuditAction {
    MEMBER_VALIDATED, SIGNUP_REJECTED,
    MEMBER_UPDATED, SIGNUP_EDITED, MEMBER_PAYMENT_METHOD_CHANGED, MEMBER_STATUS_CHANGED,
    BOOKING_BLOCK_SET, BOOKING_BLOCK_CLEARED, ACCESS_RESENT, DOG_UPDATED, DOG_LEVEL_CHANGED,
    DOG_FREE_TRAINING_CHANGED, DOG_TRANSFERRED, DOG_DEACTIVATED, DOG_REACTIVATED,
    DOG_DOCUMENT_FILE_REMOVED, FAMILY_GROUP_CHANGED,
    MEMBER_ROLES_CHANGED,
    DATA_EXPORTED,
    CATALOG_CHANGED,
    MIGRATION_APPLIED,
    PLATFORM_ROLES_CHANGED,
    ONBOARDING_COMPLETED,
    IMPERSONATION_STARTED,
    ACCOUNT_EMAIL_STATUS_CHANGED,
    PARAMETER_CHANGED,
    CLUB_UPDATED,
    CLUB_MODULES_CHANGED,
    CLUB_STATUS_CHANGED
}
