package com.agilityhub.core.platform.application.audit;

/** Implemented subset of the closed action list in S14 R-14-09. */
public enum AuditAction {
    ACTIVITY_PUBLISHED, ACTIVITY_CANCELLED, ACTIVITY_UPDATED, ACTIVITY_REGISTERED_BY_CLUB, ACTIVITY_REGISTRATION_CANCELLED_BY_CLUB,
    WEEK_VALIDATED, CLASS_CANCELLED, CLASS_UPDATED_WITH_BOOKINGS, CLASS_RISK_EXEMPTION_CHANGED, RING_BLOCK_CREATED, RING_BLOCK_CANCELLED,
    TEMPLATE_CLASS_DELETED, TEMPLATE_BAND_DELETED,
    MEMBER_VALIDATED, SIGNUP_REJECTED, SIGNUP_SUBMITTED,
    MEMBER_UPDATED, SIGNUP_EDITED, MEMBER_PAYMENT_METHOD_CHANGED, MEMBER_STATUS_CHANGED,
    BOOKING_CREATED_BY_CLUB, BOOKING_CANCELLED_BY_CLUB, BOOKING_CANCELLED_LATE,
    TRAINING_BOOKED_BY_CLUB, TRAINING_CANCELLED_BY_CLUB,
    ATTENDANCE_OVERRIDDEN,
    BOOKING_BLOCK_SET, BOOKING_BLOCK_CLEARED, ACCESS_RESENT, DOG_UPDATED, DOG_LEVEL_CHANGED,
    DOG_FREE_TRAINING_CHANGED, DOG_TRANSFERRED, DOG_DEACTIVATED, DOG_REACTIVATED,
    DOG_DOCUMENT_FILE_REMOVED, FAMILY_GROUP_CHANGED,
    MEMBER_ROLES_CHANGED,
    DATA_EXPORTED,
    CATALOG_CHANGED,
    /** S11 R-11-13 «Enviar comunicat» (E7-T01 contract, written by E7-T04): `details {recipientCount, filters}`. */
    ANNOUNCEMENT_SENT,
    MIGRATION_APPLIED,
    PLATFORM_ROLES_CHANGED,
    ONBOARDING_COMPLETED,
    IMPERSONATION_STARTED,
    ACCOUNT_EMAIL_STATUS_CHANGED,
    PARAMETER_CHANGED,
    CLUB_UPDATED,
    CLUB_MODULES_CHANGED,
    CLUB_STATUS_CHANGED,
    JOB_TRIGGERED,
    /**
     * S12 (E8-T02): the invoice state actions (R-12-16, R-12-17, R-12-19), the manual adjustment invoice (R-12-19, S12 §13)
     * and the billing run's generation and rollback (R-12-11, R-12-14; one entry per run, `details.invoiceIds[]`).
     */
    INVOICE_MARKED_PAID, INVOICE_MARKED_FAILED, INVOICE_CANCELLED, INVOICE_CREATED_MANUAL, REMITTANCE_GENERATED, REMITTANCE_ROLLED_BACK
}
